-- Oracle 
--DBCodeListLoaderTest用SQLファイル

DROP TABLE  DBCODETEST;

CREATE TABLE  DBCODETEST (
    KEY VARCHAR(10),
    VALUE VARCHAR(50),
    LANGUAGE VARCHAR(32),
    COUNTRY VARCHAR(32),
    VARIANT VARCHAR(32)
);
